// src/features/assets/DeviceAttrPanel.tsx
import * as React from 'react'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import {
  Cpu, Hand, Database, Link2, MapPin, Layers, FileStack, AlertTriangle,
} from 'lucide-react'
import { searchDevice, getBaProblems, getDeviceLink } from './api'
import type { SearchResult, BaProblem, DeviceLinkResponse } from './types'
import { FieldList, formatValue } from './FieldList'
import { RelationGraph } from './RelationGraph'
import { LinkEdgeGroup } from './LinkEdgeGroup'

interface DeviceAttrPanelProps {
  /** 当前查看的对象编号（台账设备 / 机房 / 资料域编号均可） */
  code: string | null
  /** 点击关联对象时切换当前查看对象 */
  onNavigate: (code: string) => void
}

/** 三类对象的统一称呼。资料域对象进一步说明"它是什么表里的"（电柜 / 配电箱 / 图纸回路）。 */
function kindLabel(link: DeviceLinkResponse | null): string {
  const k = link?.kind
  if (k === 'device') return link?.in_ledger === false ? '台账设备' : '台账设备'
  if (k === 'room') return '机房'
  if (k === 'record') {
    const t = link?.owner_tables?.[0]?.table_name
    return t ? `资料域 · ${t}` : '资料域对象'
  }
  return '未知'
}

/**
 * 设备属性面板（「设备属性」页右侧主体，跨对象复用）。
 *
 * 一次并取三个真实数据源，与「设备详情」抽屉同源、但以整页形式呈现，便于逐跳下钻：
 *   /search         画像 / 固定资产 / 档案 / 配件 / 别名 / 自动拓扑边
 *   /link/device/*  资料记录（按表分组）+ 关联边（**自动/人工分列**）+ owner_tables
 *   /ba/problems    BA 问题清单
 *
 * 关键：`/link/device/{code}` 现已受理 `records.device_code`，所以自动关联链上的
 * 电柜 / 配电箱 / 图纸回路都能在这里点开，链条可以从台账设备一路走到图纸回路。
 */
export function DeviceAttrPanel({ code, onNavigate }: DeviceAttrPanelProps) {
  const [loading, setLoading] = React.useState(false)
  const [search, setSearch] = React.useState<SearchResult | null>(null)
  const [link, setLink] = React.useState<DeviceLinkResponse | null>(null)
  const [baProblems, setBaProblems] = React.useState<BaProblem[]>([])

  React.useEffect(() => {
    if (!code) {
      setSearch(null)
      setLink(null)
      setBaProblems([])
      return
    }
    const target = code
    let cancelled = false
    async function load() {
      setLoading(true)
      setSearch(null)
      setLink(null)
      setBaProblems([])
      // 三源相互独立：任一不可用都不该拖垮整屏
      const [s, ba, lk] = await Promise.all([
        searchDevice(target).catch(() => null),
        getBaProblems({ device_code: target, page_size: 50 }).catch(
          () => ({ items: [] as BaProblem[], total: 0 }),
        ),
        getDeviceLink(target).catch(() => null),
      ])
      if (cancelled) return
      setSearch(s)
      setBaProblems(ba.items || [])
      setLink(lk)
      setLoading(false)
    }
    void load()
    return () => {
      cancelled = true
    }
  }, [code])

  if (!code) {
    return (
      <Card className="h-full">
        <CardContent className="py-16 text-center text-sm text-gray-500">
          从左侧搜索或树中选择一个对象，这里会显示它的属性与全部关联。
        </CardContent>
      </Card>
    )
  }

  if (loading) {
    return (
      <div className="space-y-3">
        <Skeleton className="h-28 w-full" />
        <Skeleton className="h-40 w-full" />
        <Skeleton className="h-52 w-full" />
      </div>
    )
  }

  const prof = search?.profile
  const name = link?.name || prof?.name || ''
  const primary = link?.groups?.[0]
  const attrs = (primary?.records?.[0]?.data || {}) as Record<string, unknown>
  const autoEdges = link?.edges_auto || []
  const manualEdges = link?.edges_manual || []

  // 图谱优先用 /link 的边（带来源标注），退回 /search 的拓扑边
  const graphEdges = React.useMemo(() => {
    if (link?.edges?.length) return link.edges as unknown as Record<string, unknown>[]
    return ((search?.edges || []) as unknown as Record<string, unknown>[])
  }, [link, search])

  return (
    <div className="space-y-3">
      {/* ============ 标识 ============ */}
      <Card>
        <CardHeader className="py-3">
          <CardTitle className="text-sm flex items-center gap-2 flex-wrap">
            <Badge variant="secondary" className="font-mono">{code}</Badge>
            <Badge
              variant="outline"
              className={
                link?.kind === 'device'
                  ? 'text-blue-700 border-blue-300 bg-blue-50'
                  : link?.kind === 'room'
                    ? 'text-teal-700 border-teal-300 bg-teal-50'
                    : 'text-amber-700 border-amber-300 bg-amber-50'
              }
            >
              {kindLabel(link)}
            </Badge>
            {name && name !== code && (
              <span className="text-sm font-normal text-gray-700 truncate">{name}</span>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-gray-600">
            {link?.subsystem?.name && (
              <span>子系统：<b className="text-gray-800">{link.subsystem.name}</b></span>
            )}
            {(link?.building || link?.floor) && (
              <span className="flex items-center gap-1">
                <MapPin className="w-3 h-3" />
                {[link?.building, link?.floor].filter(Boolean).join(' / ')}
              </span>
            )}
            {(prof?.room?.room_name || prof?.room?.room_code) && (
              <span>机房：<b className="text-gray-800">{prof?.room?.room_name || prof?.room?.room_code}</b></span>
            )}
            {prof?.tag_no && <span>标签：<b className="text-gray-800">{prof.tag_no}</b></span>}
            {link?.kind === 'record' && <span className="text-amber-700">未登记台账（仅资料域）</span>}
          </div>
          {link?.owner_tables && link.owner_tables.length > 0 && (
            <div className="flex flex-wrap items-center gap-1.5 text-xs">
              <FileStack className="w-3 h-3 text-gray-400" />
              <span className="text-gray-500">资料来源：</span>
              {link.owner_tables.map((t) => (
                <Badge key={t.table_id} variant="outline" className="text-[10px] font-normal">
                  {t.table_name} · {t.record_count}
                </Badge>
              ))}
            </div>
          )}
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-gray-500">
            <span className="flex items-center gap-1">
              <Database className="w-3 h-3" />资料记录 {link?.record_count ?? search?.total_records ?? 0}
            </span>
            <span className="flex items-center gap-1">
              <Layers className="w-3 h-3" />资料表 {link?.table_count ?? 0}
            </span>
            <span className="flex items-center gap-1">
              <Link2 className="w-3 h-3" />关联 {link?.edge_summary?.total ?? 0}
            </span>
          </div>
        </CardContent>
      </Card>

      {/* ============ 属性 ============ */}
      <Card>
        <CardHeader className="py-3">
          <CardTitle className="text-sm flex items-center gap-2">
            <Layers className="w-4 h-4 text-gray-500" />对象属性
            {primary && (
              <span className="text-xs font-normal text-gray-400">
                来自《{primary.table_name}》
              </span>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <FieldList data={attrs} columns={2} emptyText="该对象在资料表中暂无字段数据。" />
        </CardContent>
      </Card>

      {/* ============ 关联关系（自动 / 人工分列） ============ */}
      <Card>
        <CardHeader className="py-3">
          <CardTitle className="text-sm flex items-center gap-2 flex-wrap">
            <Link2 className="w-4 h-4 text-gray-500" />关联关系
            <span className="text-xs font-normal text-gray-400">
              共 {link?.edge_summary?.total ?? 0} 条
            </span>
            {!!link?.edge_summary?.auto && (
              <Badge className="bg-cyan-100 text-cyan-800 hover:bg-cyan-100 border-cyan-200 gap-1">
                <Cpu className="w-3 h-3" />自动 {link.edge_summary.auto}
              </Badge>
            )}
            {!!link?.edge_summary?.manual && (
              <Badge variant="secondary" className="gap-1">
                <Hand className="w-3 h-3" />人工 {link.edge_summary.manual}
              </Badge>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {autoEdges.length === 0 && manualEdges.length === 0 ? (
            <p className="text-sm text-gray-500">该对象暂无关联关系。</p>
          ) : (
            <>
              {autoEdges.length > 0 && (
                <LinkEdgeGroup title="自动关联" tone="cyan" edges={autoEdges} onNavigate={onNavigate} />
              )}
              {manualEdges.length > 0 && (
                <LinkEdgeGroup title="人工关联" tone="slate" edges={manualEdges} onNavigate={onNavigate} />
              )}
            </>
          )}
        </CardContent>
      </Card>

      {/* ============ 关联图谱 ============ */}
      <Card>
        <CardHeader className="py-3">
          <CardTitle className="text-sm">关联图谱（以当前对象为中心，可点节点下钻）</CardTitle>
        </CardHeader>
        <CardContent>
          <RelationGraph
            centerCode={code}
            edges={graphEdges}
            problems={baProblems}
            onSelectNode={onNavigate}
          />
        </CardContent>
      </Card>

      {/* ============ BA 问题 ============ */}
      {baProblems.length > 0 && (
        <Card>
          <CardHeader className="py-3">
            <CardTitle className="text-sm flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-amber-500" />BA 问题（{baProblems.length}）
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-1 text-sm">
              {baProblems.map((p, i) => (
                <li
                  key={p.id ?? i}
                  className="border-b border-dashed border-gray-100 py-1 flex flex-wrap gap-2 items-center"
                >
                  <Badge
                    variant={
                      p.status === 'closed' ? 'success' : p.status === 'processing' ? 'warning' : 'destructive'
                    }
                  >
                    {formatValue(p.status ?? '未知')}
                  </Badge>
                  <span className="text-gray-700">{formatValue(p.problem_type ?? '')}</span>
                  <span className="text-gray-400">· {formatValue(p.location ?? p.group_area ?? '')}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}
    </div>
  )
}

// vue-frontend/src/components/viz/DeviceAttrPanel.vue
<script setup lang="ts">
/**
 * 设备属性面板（「设备属性」子视图右侧主体，跨对象复用）
 * 一次并取三个真实数据源（与「设备详情」抽屉同源，但以整页形式呈现，便于逐跳下钻）：
 *   /search 画像 · /link/device 资料记录与关联边（自动/人工分列）· /ba/problems 问题。
 * 三源相互独立：任一不可用只降级为空，不拖垮整屏（见 useVizDeviceBundle）。
 */
import { computed, watch } from 'vue'
import { Collection, Link, Location, Share, Tickets } from '@element-plus/icons-vue'
import BaProblemList from '@/components/viz/BaProblemList.vue'
import FieldList from '@/components/viz/FieldList.vue'
import LinkEdgeGroup from '@/components/viz/LinkEdgeGroup.vue'
import RelationGraph from '@/components/viz/RelationGraph.vue'
import { useVizDeviceBundle } from '@/composables/useVizDeviceBundle'
import { fmtInt } from '@/lib/format'

const props = defineProps<{ code: string | null }>()
const emit = defineEmits<{ (e: 'navigate', code: string): void }>()

const { loading, search, link, problems, load } = useVizDeviceBundle()

watch(() => props.code, (c) => { void load(c ?? '') }, { immediate: true })

/** 三类对象的统一称呼；资料域对象补「它是什么表里的」（电柜 / 配电箱 / 图纸回路） */
const kindText = computed(() => {
  const k = link.value?.kind
  if (k === 'device') return '台账设备'
  if (k === 'room') return '机房'
  if (k === 'record') {
    const t = link.value?.owner_tables?.[0]?.table_name
    return t ? `资料域 · ${t}` : '资料域对象'
  }
  return '未知'
})
const kindTone = computed(() => {
  const k = link.value?.kind
  return k === 'device' ? 'primary' : k === 'room' ? 'success' : 'warning'
})

const name = computed(() => link.value?.name || search.value?.profile?.name || '')
const prof = computed(() => search.value?.profile ?? null)
const primary = computed(() => link.value?.groups?.[0] ?? null)
const attrs = computed<Record<string, unknown>>(
  () => (primary.value?.records?.[0]?.data ?? {}) as Record<string, unknown>,
)
const autoEdges = computed(() => link.value?.edges_auto ?? [])
const manualEdges = computed(() => link.value?.edges_manual ?? [])
const ownerTables = computed(() => link.value?.owner_tables ?? [])
const recordCount = computed(() => link.value?.record_count ?? search.value?.total_records ?? 0)
const tableCount = computed(() => link.value?.table_count ?? 0)
const edgeTotal = computed(() => link.value?.edge_summary?.total ?? 0)
const subsystemName = computed(() => String(link.value?.subsystem?.name ?? ''))
const placeText = computed(() => [link.value?.building, link.value?.floor].filter(Boolean).join(' / '))
const roomText = computed(() => prof.value?.room?.room_name || prof.value?.room?.room_code || '')
const tagNo = computed(() => String(prof.value?.tag_no ?? ''))

/** 图谱边归一：优先用 /link 的边（带来源标注），退回 /search 的拓扑边。 */
interface GraphEdge {
  from_code: string
  to_code: string
  other_code?: string
  relation_type?: string
  source?: string
  other_kind?: string
}
const graphEdges = computed<GraphEdge[]>(() => {
  const lk = link.value
  if (lk?.edges?.length) {
    return lk.edges.map((e) => ({
      from_code: e.from_code, to_code: e.to_code, other_code: e.other_code,
      relation_type: e.relation_type, source: e.source, other_kind: e.other_kind,
    }))
  }
  return (search.value?.edges ?? []).map((e) => ({
    from_code: String(e.from ?? ''), to_code: String(e.to ?? ''),
    relation_type: String(e.type ?? '关联'), source: 'manual', other_kind: 'unknown',
  }))
})
</script>

<template>
  <div class="dap">
    <section v-if="!code" class="panel dap__blank">
      <p class="dap__blank-text">从左侧搜索或树中选择一个对象，这里会显示它的属性与全部关联。</p>
    </section>

    <el-skeleton v-else-if="loading" :rows="8" animated />

    <div v-else class="dap__body">
      <section class="panel">
        <header class="panel-head dap__ident">
          <el-tag type="info" effect="plain" class="mono break-code">{{ code }}</el-tag>
          <el-tag :type="kindTone" effect="light">{{ kindText }}</el-tag>
          <span v-if="name && name !== code" class="dap__name ellipsis" :title="name">{{ name }}</span>
        </header>
        <div class="dap__facts">
          <span v-if="subsystemName">子系统：<b>{{ subsystemName }}</b></span>
          <span v-if="placeText" class="dap__fact">
            <el-icon :size="16"><Location /></el-icon>{{ placeText }}
          </span>
          <span v-if="roomText">机房：<b>{{ roomText }}</b></span>
          <span v-if="tagNo">标签：<b>{{ tagNo }}</b></span>
          <span v-if="link?.kind === 'record'" class="dap__flag">未登记台账（仅资料域）</span>
        </div>
        <div v-if="ownerTables.length" class="dap__ident-row">
          <el-icon :size="16" class="dap__ident-icon"><Tickets /></el-icon>
          <span class="dap__ident-label">资料来源：</span>
          <el-tag
            v-for="t in ownerTables"
            :key="t.table_id"
            size="small"
            type="info"
            effect="plain"
          >
            {{ t.table_name }} · {{ t.record_count }}
          </el-tag>
        </div>
        <div class="dap__stats">
          <span>资料记录 {{ fmtInt(recordCount) }}</span>
          <span>资料表 {{ fmtInt(tableCount) }}</span>
          <span>关联 {{ fmtInt(edgeTotal) }}</span>
        </div>
      </section>

      <section class="panel">
        <header class="panel-head">
          <h3 class="panel-title dap__title">
            <el-icon :size="16"><Collection /></el-icon>
            <span>对象属性</span>
            <span v-if="primary" class="dap__title-note">来自《{{ primary.table_name }}》</span>
          </h3>
        </header>
        <FieldList :data="attrs" :columns="2" empty-text="该对象在资料表中暂无字段数据。" />
      </section>

      <section class="panel">
        <header class="panel-head">
          <h3 class="panel-title dap__title">
            <el-icon :size="16"><Link /></el-icon>
            <span>关联关系</span>
            <span class="dap__title-note">共 {{ fmtInt(edgeTotal) }} 条</span>
          </h3>
        </header>
        <p v-if="autoEdges.length === 0 && manualEdges.length === 0" class="dap__empty">
          该对象暂无关联关系。
        </p>
        <div v-else class="dap__edges">
          <LinkEdgeGroup
            v-if="autoEdges.length"
            title="自动关联"
            tone="auto"
            :edges="autoEdges"
            @select-code="emit('navigate', $event)"
          />
          <LinkEdgeGroup
            v-if="manualEdges.length"
            title="人工关联"
            tone="manual"
            :edges="manualEdges"
            @select-code="emit('navigate', $event)"
          />
        </div>
      </section>

      <section class="panel">
        <header class="panel-head">
          <h3 class="panel-title dap__title">
            <el-icon :size="16"><Share /></el-icon>
            <span>关联图谱（以当前对象为中心，可点节点下钻）</span>
          </h3>
        </header>
        <RelationGraph
          :center-code="String(code)"
          :edges="graphEdges"
          :problems="problems"
          @select-node="emit('navigate', $event)"
        />
      </section>

      <BaProblemList v-if="problems.length" :problems="problems" />
    </div>
  </div>
</template>

<style scoped>
.dap {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
  min-width: 0;
}

.dap__body {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
  min-width: 0;
}

.dap__blank {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 220px;
}

.dap__blank-text {
  margin: 0;
  max-width: 52ch;
  text-align: center;
  font-size: var(--text-sm);
  line-height: var(--leading-body);
  color: var(--fg-2);
}

.dap__ident {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-2);
  min-width: 0;
}

.dap__name {
  flex: 1 1 160px;
  min-width: 0;
  font-size: var(--text-sm);
  color: var(--fg);
}

.dap__facts {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-1) var(--space-4);
  margin-top: var(--space-2);
  font-size: var(--text-xs);
  color: var(--fg-2);
}

.dap__fact {
  display: inline-flex;
  align-items: center;
  gap: var(--space-1);
}

.dap__flag {
  color: var(--warn-fg);
}

.dap__ident-row {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-1);
  margin-top: var(--space-2);
  min-width: 0;
  font-size: var(--text-xs);
}

.dap__ident-icon {
  color: var(--meta);
}

.dap__ident-label {
  color: var(--fg-2);
}

.dap__stats {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-4);
  margin-top: var(--space-2);
  padding-top: var(--space-2);
  border-top: 1px dashed var(--border-soft);
  font-size: var(--text-xs);
  color: var(--fg-2);
}

.dap__title {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: var(--space-2);
  font-size: var(--text-sm);
}

.dap__title-note {
  font-size: var(--text-xs);
  font-weight: var(--weight-normal);
  color: var(--muted);
}

.dap__empty {
  margin: 0;
  font-size: var(--text-sm);
  color: var(--fg-2);
}

.dap__edges {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
  min-width: 0;
}
</style>
