// src/components/asset/DeviceSearchBar.tsx
import { useEffect, useRef, useState } from 'react'
import { Search, Database, HardDrive, Tags, Loader2 } from 'lucide-react'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { assetApi } from '@/services/assetApi'
import type { DeviceSuggestItem } from '@/types/asset'

interface Props {
  value: string
  onChange: (v: string) => void
  onSearch: (code?: string) => void
  loading?: boolean
}

/** 来源徽章：区分「已登记主表 / 现场台账 / 别名」——现场台账设备占多数，必须让用户看得见 */
function sourceBadge(item: DeviceSuggestItem) {
  if (item.in_ledger) {
    return (
      <Badge variant="secondary" className="shrink-0 gap-1 font-normal">
        <Database className="w-3 h-3" />
        设备台账
      </Badge>
    )
  }
  if (item.source.startsWith('别名')) {
    return (
      <Badge variant="outline" className="shrink-0 gap-1 font-normal">
        <Tags className="w-3 h-3" />
        别名
      </Badge>
    )
  }
  return (
    <Badge variant="outline" className="shrink-0 gap-1 font-normal">
      <HardDrive className="w-3 h-3" />
      现场台账
    </Badge>
  )
}

export default function DeviceSearchBar({ value, onChange, onSearch, loading }: Props) {
  const [items, setItems] = useState<DeviceSuggestItem[]>([])
  const [open, setOpen] = useState(false)
  const [fetching, setFetching] = useState(false)
  const boxRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)
  const seqRef = useRef(0)

  /* 输入防抖取候选：真实台账设备多只存在于 records，必须由后端 suggest 检索而非前端过滤。
     仅在输入框聚焦时弹出——URL 直达（?code=xxx）初始化输入框时不得遮挡下方面板 */
  useEffect(() => {
    const key = value.trim()
    if (key.length < 2) {
      setItems([])
      setOpen(false)
      return
    }
    const seq = ++seqRef.current
    setFetching(true)
    const timer = setTimeout(async () => {
      try {
        const res = await assetApi.suggest(key, 10)
        if (seq !== seqRef.current) return
        setItems(res)
        setOpen(res.length > 0 && document.activeElement === inputRef.current)
      } catch {
        if (seq === seqRef.current) setItems([])
      } finally {
        if (seq === seqRef.current) setFetching(false)
      }
    }, 280)
    return () => clearTimeout(timer)
  }, [value])

  useEffect(() => {
    const onDocClick = (e: MouseEvent) => {
      if (boxRef.current && !boxRef.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', onDocClick)
    return () => document.removeEventListener('mousedown', onDocClick)
  }, [])

  const pick = (code: string) => {
    onChange(code)
    setOpen(false)
    onSearch(code)
  }

  return (
    <div className="space-y-2">
      <div className="flex gap-2">
        <div className="relative flex-1" ref={boxRef}>
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          {fetching && (
            <Loader2 className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 animate-spin" />
          )}
          <Input
            ref={inputRef}
            placeholder="搜索设备：编号或名称，如 PDF-107 / 配电房 / 排风机"
            value={value}
            onChange={(e) => onChange(e.target.value)}
            onFocus={() => items.length > 0 && setOpen(true)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                setOpen(false)
                onSearch()
              }
              if (e.key === 'Escape') setOpen(false)
            }}
            className="pl-10"
          />
          {open && items.length > 0 && (
            <div className="absolute z-20 mt-1 w-full rounded-md border border-input bg-background shadow-sm max-h-80 overflow-y-auto">
              {items.map((it) => (
                <button
                  key={it.code}
                  type="button"
                  onClick={() => pick(it.code)}
                  className="w-full text-left px-3 py-2 hover:bg-accent border-b border-border/50 last:border-0"
                >
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-sm font-medium text-gray-900 truncate">{it.code}</span>
                    {sourceBadge(it)}
                  </div>
                  <div className="flex items-center gap-2 mt-0.5 text-xs text-gray-500">
                    {it.name && <span className="truncate">{it.name}</span>}
                    {it.subsystem_name && <span>· {it.subsystem_name}</span>}
                    {it.tables && it.tables.length > 0 && (
                      <span className="truncate">· {it.tables.slice(0, 2).join(' / ')}</span>
                    )}
                  </div>
                </button>
              ))}
            </div>
          )}
        </div>
        <Button onClick={() => onSearch()} disabled={loading}>
          {loading ? '检索中...' : '检索设备'}
        </Button>
      </div>
      <p className="text-xs text-gray-500">
        支持设备编号、名称关键字与编号别名（移交编号 / 资产代码 / BIM 标签）模糊检索。
        真实台账设备（电柜、机房、BA 设备）多数未登记设备台账，同样可检索。
      </p>
    </div>
  )
}

// vue-frontend/src/components/ledger/DeviceSearchBar.vue
<script setup lang="ts">
/**
 * 设备检索输入栏（联想候选）
 * =====================================================================
 * 候选**必须由后端 suggest 提供**（GET /assets/search/suggest，参数名是 `q`）：
 * 现场台账设备多数只存在于 records，前端本地过滤查不到。
 *
 * 行为要点：
 *  - 输入 280ms 防抖；序号递增丢弃过期响应（快速输入不会被先回的旧结果覆盖）；
 *  - 下拉**仅在输入框聚焦时**弹出：URL 直达（?code=xxx）初始化输入框时不得遮挡下方面板；
 *  - 来源徽标区分「设备台账 / 现场台账 / 别名」——现场台账占多数，必须让用户看得见。
 */
import { onMounted, onUnmounted, ref, watch } from 'vue'
import { Loading, PriceTag, Search, Tickets } from '@element-plus/icons-vue'
import { suggestDevices } from '@/api/search'
import type { DeviceSuggestItem } from '@/types/search'

const props = defineProps<{
  modelValue: string
  loading?: boolean
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
  (e: 'search', code?: string): void
}>()

const items = ref<DeviceSuggestItem[]>([])
const open = ref(false)
const fetching = ref(false)
const rootRef = ref<HTMLElement | null>(null)

let seq = 0
let timer: number | undefined

watch(
  () => props.modelValue,
  (value) => {
    const key = value.trim()
    if (timer !== undefined) window.clearTimeout(timer)
    if (key.length < 2) {
      seq += 1
      items.value = []
      open.value = false
      fetching.value = false
      return
    }
    const mine = ++seq
    fetching.value = true
    timer = window.setTimeout(async () => {
      try {
        const result = await suggestDevices(key, 10)
        if (mine !== seq) return
        items.value = result
        open.value = result.length > 0 && document.activeElement === currentInput()
      } catch {
        if (mine === seq) items.value = []
      } finally {
        if (mine === seq) fetching.value = false
      }
    }, 280)
  },
)

/** 取到真实的 input 元素（el-input 的实例不一定是 DOM 节点） */
function currentInput(): Element | null {
  return rootRef.value?.querySelector('input') ?? null
}

function onFocus() {
  if (items.value.length > 0) open.value = true
}

function pick(item: DeviceSuggestItem) {
  emit('update:modelValue', item.code)
  open.value = false
  emit('search', item.code)
}

function submit() {
  open.value = false
  emit('search')
}

function onDocMouseDown(event: MouseEvent) {
  if (rootRef.value && !rootRef.value.contains(event.target as Node)) open.value = false
}

onMounted(() => document.addEventListener('mousedown', onDocMouseDown))
onUnmounted(() => {
  document.removeEventListener('mousedown', onDocMouseDown)
  if (timer !== undefined) window.clearTimeout(timer)
})

function sourceText(item: DeviceSuggestItem): string {
  if (item.in_ledger) return '设备台账'
  return item.source.startsWith('别名') ? '别名' : '现场台账'
}
</script>

<template>
  <div class="dsb">
    <div class="dsb__row">
      <div ref="rootRef" class="dsb__box">
        <el-input
          ref="inputRef"
          :model-value="modelValue"
          class="dsb__input"
          clearable
          aria-label="设备检索关键词"
          placeholder="搜索设备：编号或名称，如 PDF-107 / 配电房 / 排风机"
          @update:model-value="emit('update:modelValue', $event)"
          @focus="onFocus"
          @keydown.enter="submit"
          @keydown.escape="open = false"
        >
          <template #prefix><el-icon :size="16"><Search /></el-icon></template>
          <template v-if="fetching" #suffix>
            <el-icon :size="16" class="dsb__spin"><Loading /></el-icon>
          </template>
        </el-input>

        <ul v-if="open && items.length > 0" class="dsb__menu">
          <li v-for="item in items" :key="item.code">
            <button type="button" class="dsb__item" @click="pick(item)">
              <span class="dsb__item-head">
                <span class="dsb__code mono ellipsis">{{ item.code }}</span>
                <el-tag
                  size="small"
                  :type="item.in_ledger ? 'success' : 'info'"
                  effect="plain"
                  class="dsb__badge"
                >
                  <el-icon :size="16">
                    <Tickets v-if="item.in_ledger" />
                    <PriceTag v-else />
                  </el-icon>
                  <span>{{ sourceText(item) }}</span>
                </el-tag>
              </span>
              <span class="dsb__item-sub">
                <span v-if="item.name" class="ellipsis">{{ item.name }}</span>
                <span v-if="item.subsystem_name">· {{ item.subsystem_name }}</span>
                <span v-if="item.tables && item.tables.length > 0" class="ellipsis">
                  · {{ item.tables.slice(0, 2).join(' / ') }}
                </span>
              </span>
            </button>
          </li>
        </ul>
      </div>

      <el-button type="primary" :loading="loading" @click="submit">检索设备</el-button>
    </div>

    <p class="dsb__tip">
      支持设备编号、名称关键字与编号别名（移交编号 / 资产代码 / BIM 标签）模糊检索。
      真实台账设备（电柜、机房、BA 设备）多数未登记设备主表，同样可检索。
    </p>
  </div>
</template>

<style scoped>
.dsb {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
  min-width: 0;
}

.dsb__row {
  display: flex;
  gap: var(--space-2);
  min-width: 0;
}

.dsb__box {
  position: relative;
  flex: 1 1 auto;
  min-width: 0;
}

.dsb__input {
  width: 100%;
}

.dsb__spin {
  color: var(--muted);
}

/* 下拉：定位在输入框下方，最宽不超过容器（不撑破页面） */
.dsb__menu {
  position: absolute;
  z-index: var(--z-dropdown);
  top: calc(100% + var(--space-1));
  left: 0;
  right: 0;
  max-height: 320px;
  overflow: auto;
  margin: 0;
  padding: 0;
  list-style: none;
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  background: var(--surface);
  box-shadow: var(--elev-raised);
}

.dsb__item {
  display: flex;
  flex-direction: column;
  gap: 2px;
  width: 100%;
  min-width: 0;
  padding: var(--space-2) var(--space-3);
  border: none;
  border-bottom: 1px solid var(--border-soft);
  background: none;
  text-align: left;
  cursor: pointer;
  transition: background-color var(--motion-fast) var(--ease-standard);
}

.dsb__item:hover {
  background: var(--accent-soft);
}

.dsb__item-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-2);
  min-width: 0;
}

.dsb__code {
  min-width: 0;
  font-size: var(--text-sm);
  font-weight: var(--weight-emphasize);
  color: var(--fg);
}

.dsb__badge {
  flex: 0 0 auto;
}

.dsb__item-sub {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-1);
  min-width: 0;
  font-size: var(--text-xs);
  color: var(--fg-2);
}

.dsb__tip {
  margin: 0;
  font-size: var(--text-xs);
  line-height: var(--leading-body);
  color: var(--muted);
}
</style>
