// src/components/asset/GlobalSearchDialog.tsx
import { useEffect, useRef, useState } from 'react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Globe2, Table2, ArrowRight, Search } from 'lucide-react'
import { getGlobalSearch } from '@/features/assets/api'
import type { GlobalSearchResponse } from '@/features/assets/types'

interface Props {
  open: boolean
  onOpenChange: (o: boolean) => void
  /** 预填的查询词（可选，从外部带进来） */
  initialQuery?: string
  /** 点「进入并筛选」→ 跳到目标表并按该词过滤行内搜索 */
  onJump: (targetTableId: number, value: string) => void
}

/**
 * 全局资料表搜索弹窗：输入任意关键词，对每一张启用资料表都搜一遍，
 * 列出「命中哪些表 · 各命中几条 · 命中记录样例」，点表即可跳进该表并预填行内搜索框。
 */
export default function GlobalSearchDialog({ open, onOpenChange, initialQuery = '', onJump }: Props) {
  const [input, setInput] = useState(initialQuery)
  const [data, setData] = useState<GlobalSearchResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [searched, setSearched] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)

  // 打开时同步外部带入的词，并自动聚焦
  useEffect(() => {
    if (open) {
      setInput(initialQuery)
      setData(null)
      setSearched(false)
      setTimeout(() => inputRef.current?.focus(), 50)
    }
  }, [open, initialQuery])

  const run = (term: string) => {
    const q = term.trim()
    if (!q) return
    setLoading(true)
    setData(null)
    getGlobalSearch(q)
      .then((d) => { setData(d); setSearched(true) })
      .catch(() => { setData(null); setSearched(true) })
      .finally(() => setLoading(false))
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-base">
            <Globe2 className="w-4 h-4 text-emerald-600" />
            全局资料表搜索
          </DialogTitle>
          <DialogDescription className="text-xs">
            对每一张启用资料表都搜一遍：输入任意编号 / 关键词，立刻看到它散落在哪些表、各命中几条。
          </DialogDescription>
        </DialogHeader>

        <div className="flex items-center gap-2">
          <div className="relative flex-1">
            <Search className="absolute left-2.5 top-2.5 w-4 h-4 text-gray-400" />
            <Input
              ref={inputRef}
              className="pl-8"
              placeholder="输入编号 / 关键词，例如 WP-B2D4ATx4、5SN9-7…"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter') run(input) }}
            />
          </div>
          <Button onClick={() => run(input)} disabled={loading || !input.trim()}>
            {loading ? '搜索中…' : '全部搜索'}
          </Button>
        </div>

        {loading && <p className="text-sm text-gray-400 py-6 text-center">正在逐张资料表搜索…</p>}

        {!loading && searched && data && (
          <div className="space-y-3">
            <div className="flex flex-wrap items-center gap-2 text-xs text-gray-500">
              <Badge variant="secondary">{data.tables_hit} 张表命中</Badge>
              <Badge variant="secondary">{data.total_hits} 条记录</Badge>
              <span>关键词「{data.query}」</span>
            </div>

            {data.tables_hit === 0 ? (
              <p className="text-sm text-gray-400 py-6 text-center">
                已搜索全部启用资料表，没有命中的记录 —— 换个关键词试试。
              </p>
            ) : (
              data.results.map((t) => (
                <div key={t.table_id} className="rounded-md border p-3">
                  <div className="flex items-center gap-2">
                    <Table2 className="w-4 h-4 text-blue-600 shrink-0" />
                    <span className="text-sm font-medium text-gray-800 truncate">{t.name}</span>
                    {t.subsystem_name && (
                      <Badge variant="outline" className="text-xs">{t.subsystem_name}</Badge>
                    )}
                    <Badge variant="secondary" className="text-xs ml-auto">{t.hit_count} 条命中</Badge>
                  </div>

                  <div className="mt-2 space-y-1.5">
                    {t.samples.map((s) => (
                      <div key={s.id} className="flex flex-wrap items-center gap-1.5 text-xs">
                        <span className="text-gray-400 font-mono shrink-0">#{s.id}</span>
                        {s.fields.map((f, i) => (
                          <span
                            key={i}
                            className="inline-flex items-center gap-1 rounded border border-slate-200 bg-slate-50 px-1.5 py-0.5"
                            title={`${f.label}`}
                          >
                            <span className="text-gray-400">{f.label}</span>
                            <span className="font-mono text-slate-700">{f.value}</span>
                          </span>
                        ))}
                      </div>
                    ))}
                  </div>

                  <div className="mt-2 flex justify-end">
                    <Button
                      variant="outline"
                      size="sm"
                      className="gap-1"
                      onClick={() => { onOpenChange(false); onJump(t.table_id, data.query) }}
                    >
                      进入并筛选 {t.hit_count} 条
                      <ArrowRight className="w-3.5 h-3.5" />
                    </Button>
                  </div>
                </div>
              ))
            )}
          </div>
        )}

        {!loading && !searched && (
          <p className="text-sm text-gray-400 py-6 text-center">
            输入一个编号或关键词，点「全部搜索」即可跨所有资料表检索。
          </p>
        )}
      </DialogContent>
    </Dialog>
  )
}

// vue-frontend/src/components/ledger/GlobalSearchDialog.vue
<script setup lang="ts">
/**
 * 全局资料表搜索弹窗
 * =====================================================================
 * 对每一张启用资料表都搜一遍（GET /assets/link/global-search，**参数名是 q**），
 * 列出「命中哪些表 · 各命中几条 · 命中记录样例」，点「进入并筛选」跳到该表并预填行内搜索框。
 *
 * 纪律：打开时清空上一次结果（否则会把旧结果当成新查询的输出）；空结果给引导文案而非空白（AC-11）。
 */
import { nextTick, ref, watch } from 'vue'
import { Aim, ArrowRight, Grid, Search } from '@element-plus/icons-vue'
import { globalSearch } from '@/api/search'
import type { GlobalSearchResponse } from '@/types/search'

const props = withDefaults(
  defineProps<{
    modelValue: boolean
    initialQuery?: string
  }>(),
  { initialQuery: '' },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
  (e: 'jump', tableId: number, value: string): void
}>()

const input = ref('')
const data = ref<GlobalSearchResponse | null>(null)
const loading = ref(false)
const searched = ref(false)
const inputRef = ref<{ focus: () => void } | null>(null)

watch(
  () => props.modelValue,
  async (open) => {
    if (!open) return
    input.value = props.initialQuery
    data.value = null
    searched.value = false
    await nextTick()
    inputRef.value?.focus()
  },
)

async function run(term: string) {
  const keyword = term.trim()
  if (!keyword) return
  loading.value = true
  data.value = null
  try {
    data.value = await globalSearch(keyword)
  } catch {
    data.value = null
  } finally {
    loading.value = false
    searched.value = true
  }
}

function jump(tableId: number) {
  const keyword = data.value?.query ?? input.value.trim()
  emit('update:modelValue', false)
  emit('jump', tableId, keyword)
}
</script>

<template>
  <el-dialog
    :model-value="modelValue"
    title="全局资料表搜索"
    width="clamp(520px, 52vw, 780px)"
    top="8vh"
    append-to-body
    @update:model-value="emit('update:modelValue', $event)"
  >
    <p class="gsd__desc">
      对每一张启用资料表都搜一遍：输入任意编号 / 关键词，立刻看到它散落在哪些表、各命中几条。
    </p>

    <div class="gsd__bar">
      <el-input
        ref="inputRef"
        v-model="input"
        clearable
        class="gsd__q"
        aria-label="全局资料表检索关键词"
        placeholder="输入编号 / 关键词，例如 WP-B2D4ATx4、5SN9-7…"
        @keydown.enter="run(input)"
      >
        <template #prefix><el-icon :size="16"><Search /></el-icon></template>
      </el-input>
      <el-button type="primary" :loading="loading" :disabled="!input.trim()" @click="run(input)">
        全部搜索
      </el-button>
    </div>

    <div class="gsd__body">
      <p v-if="loading" class="gsd__hint" role="status">
        <el-icon :size="16" class="gsd__spin"><Aim /></el-icon>
        正在逐张资料表搜索…
      </p>

      <p v-else-if="!searched" class="gsd__hint">
        输入一个编号或关键词，点「全部搜索」即可跨所有资料表检索。
      </p>

      <template v-else-if="data">
        <p class="gsd__meta">
          <el-tag size="small" type="info" effect="light" class="tnum">{{ data.tables_hit }} 张表命中</el-tag>
          <el-tag size="small" type="info" effect="plain" class="tnum">{{ data.total_hits }} 条记录</el-tag>
          <span>关键词「{{ data.query }}」</span>
        </p>

        <p v-if="data.tables_hit === 0" class="gsd__hint">
          已搜索全部启用资料表，没有任何记录命中 —— 请更换关键词，或确认该编号是否已录入。
        </p>

        <ul v-else class="gsd__list">
          <li v-for="table in data.results" :key="table.table_id" class="gsd__item">
            <div class="gsd__item-head">
              <el-icon :size="16" class="gsd__icon"><Grid /></el-icon>
              <span class="gsd__name ellipsis" :title="table.name">{{ table.name }}</span>
              <el-tag v-if="table.subsystem_name" size="small" effect="plain">{{ table.subsystem_name }}</el-tag>
              <el-tag size="small" type="info" effect="light" class="tnum">{{ table.hit_count }} 条命中</el-tag>
            </div>

            <ul class="gsd__samples">
              <li v-for="sample in table.samples" :key="sample.id" class="gsd__sample">
                <span class="gsd__sid mono">#{{ sample.id }}</span>
                <span v-for="(field, index) in sample.fields" :key="index" class="gsd__field">
                  <span class="gsd__flabel">{{ field.label }}</span>
                  <span class="gsd__fvalue mono break-code">{{ field.value }}</span>
                </span>
              </li>
            </ul>

            <div class="gsd__item-foot">
              <el-button size="small" @click="jump(table.table_id)">
                <span>进入并筛选 {{ table.hit_count }} 条</span>
                <el-icon :size="16"><ArrowRight /></el-icon>
              </el-button>
            </div>
          </li>
        </ul>
      </template>

      <p v-else class="gsd__hint">搜索失败：请检查网络后重试，或缩小关键词范围。</p>
    </div>
  </el-dialog>
</template>

<style scoped>
.gsd__desc {
  margin: 0 0 var(--space-3);
  font-size: var(--text-xs);
  line-height: var(--leading-body);
  color: var(--fg-2);
}

.gsd__bar {
  display: flex;
  gap: var(--space-2);
  min-width: 0;
}

.gsd__q {
  flex: 1 1 auto;
  min-width: 0;
}

.gsd__body {
  margin-top: var(--space-3);
  max-height: 52vh;
  overflow: auto;
  min-width: 0;
}

.gsd__meta {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-2);
  margin: 0 0 var(--space-3);
  font-size: var(--text-xs);
  color: var(--fg-2);
}

.gsd__hint {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  margin: var(--space-4) 0;
  font-size: var(--text-sm);
  color: var(--fg-2);
}

.gsd__spin {
  color: var(--accent);
}

.gsd__list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: var(--space-3);
}

.gsd__item {
  border: 1px solid var(--border-soft);
  border-radius: var(--radius-md);
  padding: var(--space-3);
  min-width: 0;
}

.gsd__item-head {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-2);
  min-width: 0;
}

.gsd__icon {
  color: var(--accent);
}

.gsd__name {
  flex: 1 1 auto;
  min-width: 0;
  font-size: var(--text-sm);
  font-weight: var(--weight-emphasize);
  color: var(--fg);
}

.gsd__samples {
  list-style: none;
  margin: var(--space-2) 0 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: var(--space-1);
}

.gsd__sample {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-2);
  min-width: 0;
  font-size: var(--text-xs);
}

.gsd__sid {
  flex: 0 0 auto;
  color: var(--muted);
}

.gsd__field {
  display: inline-flex;
  align-items: center;
  gap: var(--space-1);
  min-width: 0;
  padding: 2px var(--space-1);
  border: 1px solid var(--border-soft);
  border-radius: var(--radius-sm);
  background: var(--surface-2);
}

.gsd__flabel {
  flex: 0 0 auto;
  color: var(--muted);
}

.gsd__fvalue {
  color: var(--fg-2);
}

.gsd__item-foot {
  display: flex;
  justify-content: flex-end;
  margin-top: var(--space-2);
}
</style>
