// vue-frontend/src/components/user/AvatarUpload.vue
<script setup lang="ts">
/**
 * 用户头像上传（用户管理 / 新建用户对话框共用）
 * =====================================================================
 * 交互对齐 React 版 AvatarUpload：选图 → 前端校验类型与 5MB 上限 → 本地预览 +
 * POST /upload/avatar（multipart 直传）→ 回填 avatar_url；可移除。
 * React 版头像底色是「蓝→紫渐变」，违反本项目紫色禁令，统一改为 --accent-soft 纯色。
 */
import { ref } from 'vue'
import { Delete, Upload } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { API_BASE } from '@/config'

const props = defineProps<{
  value?: string
  name?: string
}>()
const emit = defineEmits<{ (e: 'change', url: string): void }>()

const uploading = ref(false)
const preview = ref<string | null>(props.value ?? null)
const fileInput = ref<HTMLInputElement | null>(null)

const ALLOWED_TYPES = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp']
const MAX_SIZE = 5 * 1024 * 1024

async function uploadToServer(file: File): Promise<string> {
  const formData = new FormData()
  formData.append('file', file)
  const headers: Record<string, string> = {}
  const token = localStorage.getItem('token')
  if (token) headers.Authorization = `Bearer ${token}`
  const resp = await fetch(`${API_BASE}/upload/avatar`, { method: 'POST', headers, body: formData })
  const data = (await resp.json().catch(() => ({}))) as { avatar_url?: string; detail?: string }
  if (!resp.ok) throw new Error(data.detail || `上传失败 (${resp.status})`)
  if (!data.avatar_url) throw new Error('上传响应缺少 avatar_url')
  return data.avatar_url
}

async function onFileChange(e: Event): Promise<void> {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  if (!file) return
  if (!ALLOWED_TYPES.includes(file.type)) {
    ElMessage.error('只支持 JPG, PNG, GIF, WEBP 格式的图片')
    input.value = ''
    return
  }
  if (file.size > MAX_SIZE) {
    ElMessage.error('图片大小不能超过 5MB')
    input.value = ''
    return
  }
  // 本地预览先行（与 React 版一致：预览不等待上传结果）
  const reader = new FileReader()
  reader.onload = () => { preview.value = String(reader.result ?? '') }
  reader.readAsDataURL(file)

  uploading.value = true
  try {
    const url = await uploadToServer(file)
    preview.value = url
    emit('change', url)
    ElMessage.success('头像已上传')
  } catch (err) {
    preview.value = props.value ?? null
    ElMessage.error(err instanceof Error ? err.message : '上传头像失败')
  } finally {
    uploading.value = false
    input.value = ''
  }
}

function pick(): void {
  fileInput.value?.click()
}

function remove(): void {
  preview.value = null
  emit('change', '')
}
</script>

<template>
  <div class="avatar-up">
    <div class="avatar-up__box" :class="{ 'avatar-up__box--empty': !preview }">
      <img v-if="preview" :src="preview" alt="头像预览" class="avatar-up__img" />
      <span v-else class="avatar-up__letter">{{ name?.charAt(0) || '?' }}</span>
    </div>

    <div class="avatar-up__ops min-w-0">
      <input
        ref="fileInput"
        type="file"
        accept="image/jpeg,image/jpg,image/png,image/gif,image/webp"
        class="avatar-up__input"
        @change="onFileChange"
      />
      <div class="avatar-up__btns">
        <el-button size="small" :loading="uploading" @click="pick()">
          <el-icon v-if="!uploading" :size="16"><Upload /></el-icon>
          <span>{{ uploading ? '上传中…' : '上传头像' }}</span>
        </el-button>
        <el-button v-if="preview" size="small" text type="danger" @click="remove()">
          <el-icon :size="16"><Delete /></el-icon><span>移除</span>
        </el-button>
      </div>
      <p class="avatar-up__hint">支持 JPG, PNG, GIF, WEBP，最大 5MB</p>
    </div>
  </div>
</template>

<style scoped>
.avatar-up { display: flex; align-items: center; gap: var(--space-4); }
.avatar-up__box {
  width: 64px; height: 64px; border-radius: var(--radius-pill);
  overflow: hidden; flex: 0 0 auto;
  display: flex; align-items: center; justify-content: center;
  background: var(--accent-soft);
}
.avatar-up__img { width: 100%; height: 100%; object-fit: cover; display: block; }
.avatar-up__letter { font-size: var(--text-xl); font-weight: var(--weight-emphasize); color: var(--accent); }
.avatar-up__ops { display: flex; flex-direction: column; gap: var(--space-1); }
.avatar-up__input { display: none; }
.avatar-up__btns { display: flex; align-items: center; gap: var(--space-2); }
.avatar-up__hint { margin: 0; font-size: var(--text-xs); color: var(--muted); }
</style>

// src/components/users/AvatarUpload.tsx
import React, { useRef, useState, useEffect } from 'react'
import { X, Upload } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useToast } from '@/hooks/use-toast'
import { API_BASE } from '@/config'

interface AvatarUploadProps {
  value?: string
  onChange: (url: string) => void
  name?: string
}

export default function AvatarUpload({ value, onChange, name }: AvatarUploadProps) {
  const [uploading, setUploading] = useState(false)
  const [preview, setPreview] = useState<string | null>(value || null)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const { toast } = useToast()

  // 同步外部 value 变化
  useEffect(() => {
    if (value) {
      setPreview(value)
    }
  }, [value])

  const handleFileSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    // 检查文件类型
    const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp']
    if (!allowedTypes.includes(file.type)) {
      toast({
        title: '格式错误',
        description: '只支持 JPG, PNG, GIF, WEBP 格式的图片',
        variant: 'destructive',
      })
      return
    }

    // 检查文件大小 (最大 5MB)
    if (file.size > 5 * 1024 * 1024) {
      toast({
        title: '文件过大',
        description: '图片大小不能超过 5MB',
        variant: 'destructive',
      })
      return
    }

    // 预览图片
    const reader = new FileReader()
    reader.onload = (e) => {
      setPreview(e.target?.result as string)
    }
    reader.readAsDataURL(file)

    // 上传图片
    try {
      setUploading(true)
      const formData = new FormData()
      formData.append('file', file)
      const token = localStorage.getItem('token')
      const headers: Record<string, string> = {}
      if (token) headers['Authorization'] = `Bearer ${token}`

      const response = await fetch(`${API_BASE}/upload/avatar`, {
        method: 'POST',
        headers,
        body: formData,
      })

      if (!response.ok) {
        const error = await response.json()
        throw new Error(error.detail || '上传失败')
      }

      const data = await response.json()
      onChange(data.avatar_url)
      toast({
        title: '上传成功',
        description: '头像已上传',
      })
    } catch (error) {
      toast({
        title: '上传失败',
        description: error instanceof Error ? error.message : '上传头像失败',
        variant: 'destructive',
      })
      setPreview(value || null)
    } finally {
      setUploading(false)
    }
  }

  const handleRemove = () => {
    setPreview(null)
    onChange('')
    if (fileInputRef.current) {
      fileInputRef.current.value = ''
    }
  }

  return (
    <div className="flex items-center gap-4">
      {/* 头像预览 */}
      <div className="relative">
        <div className="w-20 h-20 rounded-full overflow-hidden bg-gradient-to-br from-blue-500 to-purple-500 flex items-center justify-center">
          {preview ? (
            <img
              src={preview.startsWith('data:') ? preview : preview}
              alt="头像"
              className="w-full h-full object-cover"
            />
          ) : (
            <span className="text-white text-2xl font-medium">
              {name?.charAt(0) || '?'}
            </span>
          )}
        </div>
        
        {/* 删除按钮 */}
        {preview && (
          <button
            type="button"
            onClick={handleRemove}
            className="absolute -top-1 -right-1 w-6 h-6 bg-red-500 text-white rounded-full flex items-center justify-center hover:bg-red-600"
          >
            <X className="w-4 h-4" />
          </button>
        )}
      </div>

      {/* 上传按钮 */}
      <div className="flex flex-col gap-2">
        <input
          ref={fileInputRef}
          type="file"
          accept="image/jpeg,image/jpg,image/png,image/gif,image/webp"
          onChange={handleFileSelect}
          className="hidden"
        />
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => fileInputRef.current?.click()}
          disabled={uploading}
        >
          {uploading ? (
            <>
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-current mr-2" />
              上传中...
            </>
          ) : (
            <>
              <Upload className="w-4 h-4 mr-2" />
              上传头像
            </>
          )}
        </Button>
        <p className="text-xs text-gray-500">
          支持 JPG, PNG, GIF, WEBP
          <br />
          最大 5MB
        </p>
      </div>
    </div>
  )
}
