// vue-frontend/src/components/user/UserFormDialog.vue
<script setup lang="ts">
/**
 * 新建 / 编辑用户对话框（用户管理）
 * =====================================================================
 * 交互对齐 React 版 UserFormDialog：
 *  - 编辑态：邮箱锁定不可改；只回传有值的 department/position/phone（avatar/name 恒传）
 *  - 新建态：邮箱/姓名/密码必填校验在父组件 handleSave 内做（与 React 版一致）；
 *    密码留空则用默认密码 123456890
 * 校验提示统一走 ElMessage，不用 el-form rules —— 与 React 版的报错时机保持等价。
 */
import { reactive, watch } from 'vue'
import { DEPARTMENTS, type User } from '@/types/user'
import AvatarUpload from './AvatarUpload.vue'

const props = defineProps<{
  /** true=编辑已有用户；false=新建 */
  user: User | null
}>()

const visible = defineModel<boolean>({ default: false })

const emit = defineEmits<{
  (e: 'save', data: Partial<User> & { password?: string }): void
}>()

const form = reactive({
  name: '',
  email: '',
  password: '123456890',
  department: '',
  position: '',
  phone: '',
  avatar: '',
})

watch(
  () => [props.user, visible.value] as const,
  ([user, open]) => {
    if (!open) return
    if (user) {
      form.name = user.name
      form.email = user.email
      form.password = ''
      form.department = user.department || ''
      form.position = user.position || ''
      form.phone = user.phone || ''
      form.avatar = user.avatar || ''
    } else {
      form.name = ''
      form.email = ''
      form.password = '123456890'
      form.department = ''
      form.position = ''
      form.phone = ''
      form.avatar = ''
    }
  },
  { immediate: true },
)

function submit(): void {
  if (props.user) {
    // 编辑模式：只传有值的可选字段（对齐 React 版）
    const payload: Partial<User> = { name: form.name, avatar: form.avatar }
    if (form.department) payload.department = form.department
    if (form.position) payload.position = form.position
    if (form.phone) payload.phone = form.phone
    emit('save', payload)
  } else {
    emit('save', {
      name: form.name,
      email: form.email,
      password: form.password,
      department: form.department || undefined,
      position: form.position || undefined,
      phone: form.phone || undefined,
      avatar: form.avatar || undefined,
    })
  }
}
</script>

<template>
  <el-dialog
    v-model="visible"
    :title="user ? '编辑用户' : '添加用户'"
    width="min(520px, 92vw)"
    append-to-body
    :close-on-click-modal="false"
  >
    <p class="udialog__desc">{{ user ? '修改用户信息' : '创建新的用户账号' }}</p>

    <el-form class="udialog__form" label-width="72px" label-position="right" @submit.prevent="submit">
      <el-form-item label="头像">
        <AvatarUpload :value="form.avatar" :name="form.name" @change="(url: string) => (form.avatar = url)" />
      </el-form-item>
      <el-form-item label="姓名" required>
        <el-input v-model="form.name" placeholder="请输入姓名" maxlength="50" />
      </el-form-item>
      <el-form-item label="邮箱" :required="!user">
        <el-input v-model="form.email" type="email" placeholder="请输入邮箱" :disabled="!!user" />
        <span v-if="user" class="udialog__hint">邮箱不可修改</span>
      </el-form-item>
      <el-form-item v-if="!user" label="密码">
        <el-input v-model="form.password" type="password" placeholder="默认密码：123456890" show-password />
        <span class="udialog__hint">不填则使用默认密码 123456890</span>
      </el-form-item>
      <el-form-item label="部门">
        <el-select v-model="form.department" placeholder="请选择部门" clearable class="udialog__select">
          <el-option v-for="dept in DEPARTMENTS" :key="dept" :value="dept" :label="dept" />
        </el-select>
      </el-form-item>
      <el-form-item label="职位">
        <el-input v-model="form.position" placeholder="请输入职位" maxlength="50" />
      </el-form-item>
      <el-form-item label="电话">
        <el-input v-model="form.phone" placeholder="请输入电话" maxlength="30" />
      </el-form-item>
    </el-form>

    <template #footer>
      <el-button @click="visible = false">取消</el-button>
      <el-button type="primary" @click="submit">{{ user ? '保存' : '创建' }}</el-button>
    </template>
  </el-dialog>
</template>

<style scoped>
.udialog__desc { margin: 0 0 var(--space-3); font-size: var(--text-sm); color: var(--muted); }
.udialog__form { padding-right: var(--space-2); }
.udialog__hint { display: block; width: 100%; font-size: var(--text-xs); color: var(--muted); line-height: var(--leading-snug); }
.udialog__select { width: 100%; min-width: 0; }
</style>

// src/components/users/UserFormDialog.tsx
import React, { useState, useEffect } from 'react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import AvatarUpload from './AvatarUpload'
import { DEPARTMENTS } from '@/types/duty'

interface User {
  id: number
  email: string
  name: string
  department?: string
  position?: string
  phone?: string
  avatar?: string
  role: string
  is_active: boolean
  created_at: string
}

interface UserFormDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  user: User | null
  onSave: (userData: Partial<User> & { password?: string }) => void
}

export default function UserFormDialog({
  open,
  onOpenChange,
  user,
  onSave,
}: UserFormDialogProps) {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '123456890',
    department: '',
    position: '',
    phone: '',
    avatar: '',
  })

  useEffect(() => {
    if (user) {
      setFormData({
        name: user.name,
        email: user.email,
        password: '',
        department: user.department || '',
        position: user.position || '',
        phone: user.phone || '',
        avatar: user.avatar || '',
      })
    } else {
      setFormData({
        name: '',
        email: '',
        password: '123456890',
        department: '',
        position: '',
        phone: '',
        avatar: '',
      })
    }
  }, [user, open])

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    
    console.log('表单提交:', { user: !!user, formData })
    
    if (user) {
      // 编辑模式：只传递有值的字段
      const updateData: Partial<User> = {
        name: formData.name,
        avatar: formData.avatar,
      }
      if (formData.department) updateData.department = formData.department
      if (formData.position) updateData.position = formData.position
      if (formData.phone) updateData.phone = formData.phone
      console.log('编辑模式，传递数据:', updateData)
      onSave(updateData)
    } else {
      // 新增模式：必须包含密码
      const dataToSave = {
        name: formData.name,
        email: formData.email,
        password: formData.password,
        department: formData.department || undefined,
        position: formData.position || undefined,
        phone: formData.phone || undefined,
        avatar: formData.avatar || undefined,
      }
      console.log('新增模式，传递数据:', dataToSave)
      onSave(dataToSave)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>
            {user ? '编辑用户' : '添加用户'}
          </DialogTitle>
          <DialogDescription>
            {user ? '修改用户信息' : '创建新的用户账号'}
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit}>
          <div className="space-y-4 py-4">
            {/* 头像上传 */}
            <div className="space-y-2">
              <Label>头像</Label>
              <AvatarUpload
                value={formData.avatar}
                onChange={(url) => setFormData({ ...formData, avatar: url })}
                name={formData.name}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="name">姓名 *</Label>
              <Input
                id="name"
                placeholder="请输入姓名"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="email">邮箱 {!user && '*'}</Label>
              <Input
                id="email"
                type="email"
                placeholder="请输入邮箱"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                required={!user}
                disabled={!!user}
              />
              {user && (
                <p className="text-xs text-gray-500">邮箱不可修改</p>
              )}
            </div>

            {!user && (
              <div className="space-y-2">
                <Label htmlFor="password">密码</Label>
                <Input
                  id="password"
                  type="password"
                  placeholder="默认密码：123456890"
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  minLength={6}
                />
                <p className="text-xs text-gray-500">不填则使用默认密码 123456890</p>
              </div>
            )}

            <div className="space-y-2">
              <Label htmlFor="department">部门</Label>
              <Select
                value={formData.department || '__none__'}
                onValueChange={(v) => setFormData({ ...formData, department: v === '__none__' ? '' : v })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="请选择部门" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="__none__">不指定</SelectItem>
                  {DEPARTMENTS.map(dept => (
                    <SelectItem key={dept} value={dept}>{dept}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="position">职位</Label>
              <Input
                id="position"
                placeholder="请输入职位"
                value={formData.position}
                onChange={(e) => setFormData({ ...formData, position: e.target.value })}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="phone">电话</Label>
              <Input
                id="phone"
                type="tel"
                placeholder="请输入电话"
                value={formData.phone}
                onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
              />
            </div>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
              取消
            </Button>
            <Button type="submit">
              {user ? '保存' : '创建'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
