// src/components/scan/DeviceLocationForm.tsx
import * as React from 'react'
import { MapPin, Save } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useToast } from '@/hooks/use-toast'
import { scanUpdateDevice } from '@/features/scan/api'
import type { ScanDevice, ScanRoom } from '@/features/scan/types'

interface Props {
  device: ScanDevice
  rooms: ScanRoom[]
  onSaved?: (updated: ScanDevice) => void
}

/**
 * 位置补录表单（扫码现场用）：
 * 楼栋 → 楼层 → 机房三级联动选择（数据源 rooms 516），选中机房自动带出楼栋/楼层；
 * 也可不选机房仅手填楼栋/楼层/位置描述。保存走 PUT /assets/devices/{id}（后端级联校验房间存在）。
 */
export function DeviceLocationForm({ device, rooms, onSaved }: Props) {
  const { toast } = useToast()
  const [saving, setSaving] = React.useState(false)
  const [building, setBuilding] = React.useState(device.building ?? '')
  const [floor, setFloor] = React.useState(device.floor ?? '')
  const [roomCode, setRoomCode] = React.useState('')
  const [locationDesc, setLocationDesc] = React.useState(device.location_desc ?? '')

  const active = React.useMemo(() => rooms.filter((r) => r.is_active !== false), [rooms])
  const buildings = React.useMemo(
    () => Array.from(new Set(active.map((r) => r.building).filter(Boolean))).sort(),
    [active],
  )
  const floors = React.useMemo(
    () => Array.from(new Set(active.filter((r) => r.building === building).map((r) => r.floor).filter(Boolean))).sort(),
    [active, building],
  )
  const roomOptions = React.useMemo(
    () => active.filter((r) => r.building === building && (!floor || r.floor === floor)),
    [active, building, floor],
  )

  const pickRoom = (code: string) => {
    setRoomCode(code)
    const room = active.find((r) => r.code === code)
    if (room) {
      setBuilding(room.building)
      setFloor(room.floor)
    }
  }

  const save = async () => {
    const room = roomCode ? active.find((r) => r.code === roomCode) : undefined
    setSaving(true)
    try {
      const updated = await scanUpdateDevice(device.id, {
        room_id: room ? room.id : null,
        building: room ? room.building : building,
        floor: room ? room.floor : floor,
        location_desc: locationDesc.trim(),
      })
      toast({ title: '位置已保存', description: updated.device_code })
      onSaved?.(updated)
    } catch (e) {
      toast({
        title: '保存失败',
        description: e instanceof Error ? e.message : '',
        variant: 'destructive',
      })
    } finally {
      setSaving(false)
    }
  }

  const canSave = building.trim() !== '' || floor.trim() !== '' || locationDesc.trim() !== '' || roomCode !== ''
  const roomLabel = (r: ScanRoom) => `${r.code}（${r.name}）`

  return (
    <div className="space-y-3">
      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-1.5">
          <Label>楼栋</Label>
          <select
            value={building}
            onChange={(e) => { setBuilding(e.target.value); setRoomCode('') }}
            className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
          >
            <option value="">未指定</option>
            {buildings.map((b) => <option key={b} value={b}>{b}</option>)}
          </select>
        </div>
        <div className="space-y-1.5">
          <Label>楼层</Label>
          <select
            value={floor}
            onChange={(e) => { setFloor(e.target.value); setRoomCode('') }}
            className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
          >
            <option value="">未指定</option>
            {floors.map((f) => <option key={f} value={f}>{f}</option>)}
          </select>
        </div>
      </div>

      <div className="space-y-1.5">
        <Label>机房（数据源 516 间 · 按楼栋/楼层过滤）</Label>
        <select
          value={roomCode}
          onChange={(e) => pickRoom(e.target.value)}
          className="w-full h-9 rounded-md border border-input bg-background px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
        >
          <option value="">不选机房（可手动填楼栋楼层）</option>
          {roomOptions.map((r) => <option key={r.id} value={r.code}>{roomLabel(r)}</option>)}
        </select>
      </div>

      <div className="space-y-1.5">
        <Label>位置描述（现场定位细节，如“3F-A 区走道尽头”）</Label>
        <Input value={locationDesc} onChange={(e) => setLocationDesc(e.target.value)} placeholder="柜号 / 参照物 / 图纸标注" />
      </div>

      <Button onClick={save} disabled={saving || !canSave} className="w-full">
        {saving ? <span className="animate-pulse">保存中</span> : (
          <>
            <Save className="w-4 h-4 mr-2" />
            保存位置
          </>
        )}
      </Button>
      <p className="text-xs text-gray-500 flex items-center gap-1">
        <MapPin className="w-3.5 h-3.5" />
        位置同时作为资产可视化区域树的挂靠依据
      </p>
    </div>
  )
}

// vue-frontend/src/components/scan/DeviceLocationForm.vue
<script setup lang="ts">
/**
 * 位置补录表单（扫码现场用）：
 * 楼栋 → 楼层 → 机房三级联动选择（数据源 rooms），选中机房自动带出楼栋/楼层；
 * 也可不选机房仅手填楼栋/楼层/位置描述。保存走 PUT /assets/devices/{id}（后端级联校验房间存在）。
 */
import { computed, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Location } from '@element-plus/icons-vue'
import { scanUpdateDevice } from '@/api/scan'
import type { ScanDevice, ScanRoom } from '@/types/scan'

const props = defineProps<{
  device: ScanDevice
  rooms: ScanRoom[]
  onSaved?: (updated: ScanDevice) => void
}>()

const saving = ref(false)
const building = ref(props.device.building ?? '')
const floor = ref(props.device.floor ?? '')
const roomCode = ref('')
const locationDesc = ref(props.device.location_desc ?? '')

const active = computed(() => props.rooms.filter((r) => r.is_active !== false))
const buildings = computed(() =>
  Array.from(new Set(active.value.map((r) => r.building).filter(Boolean))).sort(),
)
const floors = computed(() =>
  Array.from(
    new Set(
      active.value.filter((r) => r.building === building.value).map((r) => r.floor).filter(Boolean),
    ),
  ).sort(),
)
const roomOptions = computed(() =>
  active.value.filter((r) => r.building === building.value && (!floor.value || r.floor === floor.value)),
)

/** 楼栋/楼层变更即清空机房选择：机房与楼栋楼层必须一致，不允许出现矛盾组合 */
function onBuildingChange() {
  roomCode.value = ''
}
function onFloorChange() {
  roomCode.value = ''
}

function onRoomPick(code: string) {
  roomCode.value = code
  const room = active.value.find((r) => r.code === code)
  if (room) {
    building.value = room.building
    floor.value = room.floor
  }
}

const canSave = computed(
  () =>
    building.value.trim() !== '' ||
    floor.value.trim() !== '' ||
    locationDesc.value.trim() !== '' ||
    roomCode.value !== '',
)

async function save() {
  const room = roomCode.value ? active.value.find((r) => r.code === roomCode.value) : undefined
  saving.value = true
  try {
    const updated = await scanUpdateDevice(props.device.id, {
      room_id: room ? room.id : null,
      building: room ? room.building : building.value,
      floor: room ? room.floor : floor.value,
      location_desc: locationDesc.value.trim(),
    })
    ElMessage({ type: 'success', message: `位置已保存：${updated.device_code}` })
    props.onSaved?.(updated)
  } catch (e) {
    ElMessage({ type: 'error', message: `保存失败：${e instanceof Error ? e.message : ''}`, duration: 4000 })
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <div class="loc-form">
    <el-form label-position="top" size="default" @submit.prevent>
      <div class="loc-form__grid">
        <el-form-item label="楼栋">
          <el-select v-model="building" aria-label="楼栋" @change="onBuildingChange">
            <el-option label="未指定" value="" />
            <el-option v-for="b in buildings" :key="b" :label="b" :value="b" />
          </el-select>
        </el-form-item>
        <el-form-item label="楼层">
          <el-select v-model="floor" aria-label="楼层" @change="onFloorChange">
            <el-option label="未指定" value="" />
            <el-option v-for="f in floors" :key="f" :label="f" :value="f" />
          </el-select>
        </el-form-item>
      </div>

      <el-form-item :label="`机房（共 ${rooms.length} 间 · 按楼栋/楼层过滤）`">
        <el-select v-model="roomCode" aria-label="机房" @change="onRoomPick">
          <el-option label="不选机房（可手动填楼栋楼层）" value="" />
          <el-option
            v-for="r in roomOptions"
            :key="r.id"
            :label="`${r.code}（${r.name}）`"
            :value="r.code"
          />
        </el-select>
      </el-form-item>

      <el-form-item label="位置描述（现场定位细节，如「3F-A 区走道尽头」）">
        <el-input
          v-model="locationDesc"
          placeholder="柜号 / 参照物 / 图纸标注"
          aria-label="位置描述"
        />
      </el-form-item>

      <el-button type="primary" class="loc-form__save" :loading="saving" :disabled="!canSave" @click="save">
        保存位置
      </el-button>
      <p class="loc-form__note">
        <el-icon :size="14"><Location /></el-icon>
        <span>位置同时作为资产可视化区域树的挂靠依据</span>
      </p>
    </el-form>
  </div>
</template>

<style scoped>
.loc-form { min-width: 0; }
.loc-form__grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: var(--space-3); }
.loc-form :deep(.el-select) { width: 100%; }
.loc-form__save { width: 100%; }
.loc-form__note {
  display: flex; align-items: center; gap: var(--space-1);
  margin: var(--space-2) 0 0;
  font-size: var(--text-xs); color: var(--muted);
}
</style>
