// vue-frontend/src/components/viz/DeviceDetailDrawer.vue
<script setup lang="ts">
/**
 * 设备详情抽屉（区域树 / 子系统树 / 设备层级 / BA / 检索 / 属性 共用，挂在 VizLayout 层）
 * =====================================================================
 * 一次并取四个真实数据源，任一不可用都不拖垮整屏（见 useVizDeviceBundle）：
 *   /search        画像 / 固定资产 / 档案 / 配件 / 别名 / BA 问题 / 机房
 *   /link/device/* 资料记录（按表分组）+ 关联边（自动/人工分列）+ owner_tables
 *   /ba/problems   该对象的 BA 问题清单
 *   /geo-observations 扫码现场定位（仅本抽屉取，属性面板不取）
 * 打开状态由 URL ?code= 驱动（深链直达），本组件只反映 props。
 */
import { computed, watch } from 'vue'
import { ArrowRight, Cpu, Link, Share, User } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import assetApi from '@/api/assetApi'
import BaProblemList from '@/components/viz/BaProblemList.vue'
import DeviceProfileCard from '@/components/viz/DeviceProfileCard.vue'
import FieldList from '@/components/viz/FieldList.vue'
import GeoPanel from '@/components/viz/GeoPanel.vue'
import LinkEdgeGroup from '@/components/viz/LinkEdgeGroup.vue'
import RecordGroupList from '@/components/viz/RecordGroupList.vue'
import RelationGraph from '@/components/viz/RelationGraph.vue'
import { useVizDeviceBundle } from '@/composables/useVizDeviceBundle'
import { fmtInt } from '@/lib/format'

const props = defineProps<{ open: boolean; deviceCode: string | null }>()
const emit = defineEmits<{
  (e: 'update:open', v: boolean): void
  (e: 'navigate', code: string): void
  (e: 'go-link'): void
  (e: 'go-table', tableId: number): void
}>()

const { loading, search, link, problems, geo, load, reset } = useVizDeviceBundle()

watch(
  () => [props.open, props.deviceCode] as const,
  ([open, code]) => {
    if (open && code) void load(code, true)
    else reset()
  },
  { immediate: true },
)

const code = computed(() => props.deviceCode ?? '')
const prof = computed(() => search.value?.profile ?? null)
const name = computed(() => link.value?.name || prof.value?.name || search.value?.target?.name || code.value)
const edgeSummary = computed(() => link.value?.edge_summary ?? null)
const groups = computed(() => link.value?.groups ?? [])
const aliases = computed(() => search.value?.aliases ?? [])
const accessories = computed(() => search.value?.accessories ?? [])
const fixedAsset = computed(() => search.value?.fixed_asset ?? null)
const archive = computed(() => search.value?.archive ?? null)
const autoEdges = computed(() => link.value?.edges_auto ?? [])
const manualEdges = computed(() => link.value?.edges_manual ?? [])
const totalRecords = computed(() => link.value?.record_count ?? search.value?.total_records ?? 0)

interface GraphEdge {
  from_code: string
  to_code: string
  other_code?: string
  relation_type?: string
  source?: string
  other_kind?: string
}
/** 图谱边归一：优先用 /link 的边（带来源标注），退回 /search 的拓扑边 */
const graphEdges = computed<GraphEdge[]>(() => {
  const lk = link.value
  if (lk?.edges?.length) {
    return lk.edges.map((e) => ({
      from_code: e.from_code, to_code: e.to_code, other_code: e.other_code,
      relation_type: e.relation_type, source: e.source, other_kind: e.other_kind,
    }))
  }
  return (search.value?.edges ?? []).map((e) => ({
    from_code: String(e.from ?? ''), to_code: String(e.to ?? ''),
    relation_type: String(e.type ?? '关联'), source: 'manual', other_kind: 'unknown',
  }))
})

async function removeEdge(id: number) {
  try {
    await ElMessageBox.confirm(
      '确定删除该关联边？删除只影响链路关系，双方设备的资料与记录均保留。',
      '删除关联',
      { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' },
    )
  } catch {
    return
  }
  try {
    await assetApi.deleteRelation(id)
    ElMessage({ type: 'success', message: '关联已删除' })
    if (props.deviceCode) await load(props.deviceCode, true)
  } catch (e) {
    ElMessage({ type: 'error', message: `删除失败：${e instanceof Error ? e.message : String(e)}` })
  }
}

const hasContent = computed(() => !!search.value || !!link.value)
</script>

<template>
  <el-drawer
    :model-value="open"
    direction="rtl"
    size="min(94vw, 880px)"
    append-to-body
    :with-header="false"
    @close="emit('update:open', false)"
  >
    <header class="ddr__head">
      <h2 class="ddr__title">设备详情</h2>
      <el-tag v-if="code" type="info" effect="plain" class="mono break-code">{{ code }}</el-tag>
      <span v-if="name && name !== code" class="ddr__name ellipsis" :title="name">{{ name }}</span>
      <span v-if="edgeSummary && edgeSummary.total > 0" class="ddr__tags">
        <el-tag v-if="edgeSummary.auto > 0" size="small" type="primary" effect="light">
          <el-icon :size="16"><Cpu /></el-icon>自动 {{ edgeSummary.auto }}
        </el-tag>
        <el-tag v-if="edgeSummary.manual > 0" size="small" type="info" effect="light">
          <el-icon :size="16"><User /></el-icon>人工 {{ edgeSummary.manual }}
        </el-tag>
      </span>
    </header>

    <div class="ddr__body">
      <el-skeleton v-if="loading" :rows="8" animated />

      <p v-else-if="!hasContent" class="ddr__empty">未检索到该对象的信息。</p>

      <div v-else class="ddr__content">
        <DeviceProfileCard
          :prof="prof"
          :link="link"
          :total-records="totalRecords"
          :edge-total="edgeSummary?.total ?? 0"
          :aliases="aliases"
        />

        <GeoPanel :geo="geo" :name="name" />

        <section class="panel">
          <header class="panel-head ddr__sec-head">
            <h3 class="panel-title ddr__sec-title">
              <el-icon :size="16"><Link /></el-icon>
              <span>关联关系</span>
              <span class="ddr__note">共 {{ fmtInt(edgeSummary?.total ?? 0) }} 条</span>
            </h3>
            <el-button size="small" text @click="emit('go-link')">
              <span>联动中心</span>
              <el-icon :size="16"><ArrowRight /></el-icon>
            </el-button>
          </header>
          <p v-if="autoEdges.length === 0 && manualEdges.length === 0" class="ddr__empty">
            该对象暂无关联关系。
          </p>
          <div v-else class="ddr__edges">
            <LinkEdgeGroup
              v-if="autoEdges.length"
              title="自动关联"
              tone="auto"
              :edges="autoEdges"
              @select-code="emit('navigate', $event)"
              @delete="removeEdge"
            />
            <LinkEdgeGroup
              v-if="manualEdges.length"
              title="人工关联"
              tone="manual"
              :edges="manualEdges"
              @select-code="emit('navigate', $event)"
              @delete="removeEdge"
            />
          </div>
        </section>

        <section class="panel">
          <header class="panel-head">
            <h3 class="panel-title ddr__sec-title">
              <el-icon :size="16"><Share /></el-icon>
              <span>关联图谱（以当前对象为中心）</span>
            </h3>
          </header>
          <RelationGraph
            :center-code="code"
            :edges="graphEdges"
            :problems="problems"
            @select-node="emit('navigate', $event)"
          />
        </section>

        <section class="panel">
          <header class="panel-head">
            <h3 class="panel-title ddr__sec-title">
              <el-icon :size="16"><Link /></el-icon>
              <span>资料记录（{{ totalRecords }}）</span>
              <span class="ddr__note">{{ groups.length }} 张表 · 与「数据表管理」同源</span>
            </h3>
          </header>
          <RecordGroupList :groups="groups" @open-table="emit('go-table', $event)" />
        </section>

        <section v-if="fixedAsset" class="panel">
          <header class="panel-head">
            <h3 class="panel-title ddr__sec-title"><span>固定资产</span></h3>
          </header>
          <FieldList :data="fixedAsset" :columns="2" empty-text="无" />
        </section>

        <section v-if="archive" class="panel">
          <header class="panel-head">
            <h3 class="panel-title ddr__sec-title"><span>设备档案</span></h3>
          </header>
          <FieldList :data="archive" :columns="2" empty-text="无" />
        </section>

        <BaProblemList :problems="problems" empty-text="无" />

        <section v-if="accessories.length" class="panel">
          <header class="panel-head">
            <h3 class="panel-title ddr__sec-title"><span>配件（{{ accessories.length }}）</span></h3>
          </header>
          <div class="ddr__acc">
            <FieldList v-for="(a, i) in accessories" :key="i" :data="a" :columns="2" empty-text="—" />
          </div>
        </section>
      </div>
    </div>
  </el-drawer>
</template>

<style scoped>
.ddr__head {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-2);
  margin-bottom: var(--space-3);
  min-width: 0;
}

.ddr__title {
  margin: 0;
  font-size: var(--text-lg);
  font-weight: var(--weight-emphasize);
  color: var(--fg);
}

.ddr__name {
  flex: 1 1 120px;
  min-width: 0;
  font-size: var(--text-sm);
  color: var(--fg-2);
}

.ddr__tags {
  display: inline-flex;
  flex-wrap: wrap;
  gap: var(--space-1);
  margin-left: auto;
}

.ddr__body {
  min-width: 0;
}

.ddr__content {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
  min-width: 0;
}

.ddr__empty {
  margin: 0;
  padding: var(--space-6) 0;
  text-align: center;
  font-size: var(--text-sm);
  color: var(--fg-2);
}

.ddr__sec-head {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-2);
}

.ddr__sec-title {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: var(--space-2);
  font-size: var(--text-sm);
}

.ddr__note {
  font-size: var(--text-xs);
  font-weight: var(--weight-normal);
  color: var(--muted);
}

.ddr__edges {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
  min-width: 0;
}

.ddr__acc {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
}
</style>

// src/features/assets/DeviceDetailDrawer.tsx
import * as React from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Dialog, DialogContent, DialogHeader, DialogTitle,
} from '@/components/ui/dialog'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { useToast } from '@/hooks/use-toast'
import {
  Cpu, Hand, Database, ChevronRight, ExternalLink, Link2,
  MapPin, Image as ImageIcon, Layers, AlertTriangle, Wrench, Tag,
} from 'lucide-react'
import { searchDevice, getBaProblems, getDeviceLink } from './api'
import type {
  SearchResult, BaProblem, DeviceLinkResponse, DeviceLinkEdge,
} from './types'
import { FieldList, formatValue } from './FieldList'
import { RelationGraph } from './RelationGraph'

interface DeviceDetailDrawerProps {
  /** 当前设备编号；为 null 时抽屉关闭 */
  deviceCode: string | null
  open: boolean
  onOpenChange: (open: boolean) => void
  /** 关联图谱中点击某节点时，跳转到该设备（在当前抽屉内联动） */
  onNavigate?: (code: string) => void
}

/**
 * 设备详情抽屉（区域树 / 子系统树 / 设备层级 / BA / 检索 共用）。
 *
 * 2026-09-15 重做：改造前只读 `/search` 的 `device` 字段（后端根本没这个字段），
 * 于是「基础信息 / 关联设备」整块永远空白 —— 这是"像死数据"的直接原因。
 * 现在一次并取三个真实数据源，全部落到位：
 *   /search          画像 profile / 固定资产 / 档案 / 配件 / 别名 / BA 问题 / 机房
 *   /link/device/*   资料记录（按资料表分组）+ 关联边（**自动/人工分列**）+ 分组统计
 *   /ba/problems     该设备的 BA 问题清单
 */
export function DeviceDetailDrawer({ deviceCode, open, onOpenChange, onNavigate }: DeviceDetailDrawerProps) {
  const { toast } = useToast()
  const navigate = useNavigate()
  const [loading, setLoading] = React.useState(false)
  const [search, setSearch] = React.useState<SearchResult | null>(null)
  const [link, setLink] = React.useState<DeviceLinkResponse | null>(null)
  const [baProblems, setBaProblems] = React.useState<BaProblem[]>([])
  const [expanded, setExpanded] = React.useState<Record<number, boolean>>({})

  React.useEffect(() => {
    if (!open || !deviceCode) return
    const code = deviceCode
    let cancelled = false
    async function load() {
      setLoading(true)
      setSearch(null)
      setLink(null)
      try {
        // 三个源相互独立：link 是新增能力，旧后端没有时不能拖垮整屏
        const [s, ba, lk] = await Promise.all([
          searchDevice(code).catch(() => null),
          getBaProblems({ device_code: code, page_size: 100 }).catch(() => ({ items: [] as BaProblem[], total: 0 })),
          getDeviceLink(code).catch(() => null),
        ])
        if (cancelled) return
        setSearch(s)
        setBaProblems(ba.items || [])
        setLink(lk)
      } catch (e) {
        if (!cancelled) {
          toast({
            title: '加载设备详情失败',
            description: e instanceof Error ? e.message : '',
            variant: 'destructive',
          })
        }
      } finally {
        if (!cancelled) setLoading(false)
      }
    }
    void load()
    return () => { cancelled = true }
  }, [open, deviceCode, toast])

  const code = deviceCode ?? ''
  const prof = search?.profile
  const name = link?.name || prof?.name || search?.target?.name || code
  const edgeSummary = link?.edge_summary
  const groups = link?.groups || []
  const totalRecords = link?.record_count ?? search?.total_records ?? 0

  // 图谱用 /search 的完整 edges（含 type），叠加 link 的来源标注
  const originByKey = React.useMemo(() => {
    const m: Record<string, string> = {}
    for (const e of link?.edges || []) {
      m[`${e.from_code}->${e.to_code}`] = e.source
    }
    return m
  }, [link])
  const graphEdges = React.useMemo(() => {
    const raw = (search?.edges || []) as unknown as Record<string, unknown>[]
    return raw.map((e) => {
      const f = String(e.from ?? e.from_code ?? '')
      const t = String(e.to ?? e.to_code ?? '')
      return {
        ...e,
        from_code: f,
        to_code: t,
        relation_type: String(e.relation_type ?? e.type ?? '关联'),
        source: originByKey[`${f}->${t}`] || originByKey[`${t}->${f}`] || 'manual',
      }
    })
  }, [search, originByKey])

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[88vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 flex-wrap">
            <span>设备详情</span>
            <Badge variant="secondary" className="font-mono">{code}</Badge>
            {name && name !== code && (
              <span className="text-base font-normal text-gray-600">{name}</span>
            )}
            {edgeSummary && edgeSummary.total > 0 && (
              <span className="flex items-center gap-1.5 ml-auto">
                {edgeSummary.auto > 0 && (
                  <Badge className="bg-cyan-100 text-cyan-800 hover:bg-cyan-100 border-cyan-200 gap-1">
                    <Cpu className="w-3 h-3" />自动 {edgeSummary.auto}
                  </Badge>
                )}
                {edgeSummary.manual > 0 && (
                  <Badge variant="secondary" className="gap-1">
                    <Hand className="w-3 h-3" />人工 {edgeSummary.manual}
                  </Badge>
                )}
              </span>
            )}
          </DialogTitle>
        </DialogHeader>

        {loading && (
          <div className="space-y-3">
            <Skeleton className="h-24 w-full" />
            <Skeleton className="h-40 w-full" />
            <Skeleton className="h-32 w-full" />
          </div>
        )}

        {!loading && !search && !link && (
          <p className="text-sm text-gray-500 py-8 text-center">未检索到该设备的信息。</p>
        )}

        {!loading && (search || link) && (
          <div className="space-y-4">
            {/* ============ 画像 ============ */}
            <Card>
              <CardHeader className="py-3">
                <CardTitle className="text-sm flex items-center gap-2">
                  <Layers className="w-4 h-4 text-gray-500" />设备画像
                  {prof ? (
                    prof.in_ledger
                      ? <Badge variant="outline" className="text-green-700 border-green-300 bg-green-50">已登记台账</Badge>
                      : <Badge variant="outline" className="text-amber-700 border-amber-300 bg-amber-50">未登记（仅资料）</Badge>
                  ) : null}
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                  <MiniStat icon={<Database className="w-3.5 h-3.5" />} label="资料记录" value={totalRecords} />
                  <MiniStat icon={<Layers className="w-3.5 h-3.5" />} label="涉及资料表" value={link?.table_count ?? prof?.source_tables?.length ?? 0} />
                  <MiniStat icon={<Link2 className="w-3.5 h-3.5" />} label="关联关系" value={edgeSummary?.total ?? 0} />
                  <MiniStat icon={<ImageIcon className="w-3.5 h-3.5" />} label="现场照片" value={prof?.photo_count ?? 0} />
                </div>
                <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-gray-600">
                  {prof?.subsystem_name && (
                    <span>子系统：<b className="text-gray-800">{prof.subsystem_name}</b></span>
                  )}
                  {(prof?.building || link?.building) && (
                    <span className="flex items-center gap-1">
                      <MapPin className="w-3 h-3" />
                      {[prof?.building || link?.building, prof?.floor || link?.floor, prof?.location || '']
                        .filter(Boolean).join(' / ')}
                    </span>
                  )}
                  {(prof?.room || link?.groups) && (
                    <span>
                      机房：
                      <b className="text-gray-800">
                        {prof?.room?.room_name || prof?.room?.room_code || '—'}
                      </b>
                    </span>
                  )}
                  {prof?.tag_no && <span>标签：<b className="text-gray-800">{prof.tag_no}</b></span>}
                </div>
                {search?.aliases && search.aliases.length > 0 && (
                  <div className="flex flex-wrap items-center gap-2 text-xs">
                    <Tag className="w-3 h-3 text-gray-400" />
                    <span className="text-gray-500">编号别名：</span>
                    {search.aliases.map((a, i) => (
                      <Badge key={i} variant="outline" className="font-mono text-[10px]">
                        {formatValue(a.alias_code ?? a.alias ?? a)}
                      </Badge>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* ============ 关联关系（自动 / 人工分列） ============ */}
            <Card>
              <CardHeader className="py-3">
                <CardTitle className="text-sm flex items-center gap-2 flex-wrap">
                  <Link2 className="w-4 h-4 text-gray-500" />关联关系
                  <span className="text-xs font-normal text-gray-400">
                    共 {edgeSummary?.total ?? 0} 条
                  </span>
                  {!!edgeSummary?.auto && (
                    <Badge className="bg-cyan-100 text-cyan-800 hover:bg-cyan-100 border-cyan-200 gap-1">
                      <Cpu className="w-3 h-3" />自动 {edgeSummary.auto}
                    </Badge>
                  )}
                  {!!edgeSummary?.manual && (
                    <Badge variant="secondary" className="gap-1">
                      <Hand className="w-3 h-3" />人工 {edgeSummary.manual}
                    </Badge>
                  )}
                  <Button
                    variant="ghost" size="sm" className="ml-auto h-7 text-xs"
                    onClick={() => { onOpenChange(false); navigate('/asset-viz?tab=link') }}
                  >
                    <ExternalLink className="w-3 h-3 mr-1" />联动中心
                  </Button>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {(link?.edges || []).length === 0 ? (
                  <p className="text-sm text-gray-500">该设备暂无关联关系。</p>
                ) : (
                  <>
                    {link?.edges_auto && link.edges_auto.length > 0 && (
                      <EdgeGroup title="自动关联" tone="cyan" icon={<Cpu className="w-3.5 h-3.5" />}
                        edges={link.edges_auto} onNavigate={onNavigate} />
                    )}
                    {link?.edges_manual && link.edges_manual.length > 0 && (
                      <EdgeGroup title="人工关联" tone="slate" icon={<Hand className="w-3.5 h-3.5" />}
                        edges={link.edges_manual} onNavigate={onNavigate} />
                    )}
                  </>
                )}
              </CardContent>
            </Card>

            {/* ============ 关联图谱 ============ */}
            <Card>
              <CardHeader className="py-3">
                <CardTitle className="text-sm">关联图谱（以当前对象为中心）</CardTitle>
              </CardHeader>
              <CardContent>
                <RelationGraph
                  centerCode={code}
                  edges={link?.edges && link.edges.length ? link.edges : graphEdges}
                  problems={baProblems}
                  onSelectNode={(c) => onNavigate?.(c)}
                />
              </CardContent>
            </Card>

            {/* ============ 资料记录（按子系统 → 资料表分组，与数据表管理同源） ============ */}
            <Card>
              <CardHeader className="py-3">
                <CardTitle className="text-sm flex items-center gap-2">
                  <Database className="w-4 h-4 text-gray-500" />
                  资料记录（{totalRecords}）
                  <span className="text-xs font-normal text-gray-400">
                    {groups.length} 张表 · 与「数据表管理」同源
                  </span>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                {groups.length === 0 ? (
                  <p className="text-sm text-gray-500">
                    该编号在资料表中暂无记录（可能它是台账设备但没有对应资料行）。
                  </p>
                ) : groups.map((g) => {
                  const isOpen = !!expanded[g.table_id]
                  return (
                    <div key={g.table_id} className="rounded-lg border">
                      <button
                        type="button"
                        className="w-full flex items-center gap-2 px-3 py-2 text-left hover:bg-gray-50"
                        onClick={() => setExpanded((p) => ({ ...p, [g.table_id]: !isOpen }))}
                      >
                        <ChevronRight className={`w-4 h-4 text-gray-400 transition-transform ${isOpen ? 'rotate-90' : ''}`} />
                        <span className="text-sm font-medium">{g.table_name}</span>
                        {g.subsystem && (
                          <Badge variant="outline" className="text-[10px]">{g.subsystem.name}</Badge>
                        )}
                        <Badge variant="secondary" className="text-[10px] ml-auto">{g.records.length} 条</Badge>
                        <span
                          role="link"
                          tabIndex={0}
                          className="text-xs text-blue-600 hover:underline flex items-center gap-0.5"
                          onClick={(ev) => {
                            ev.stopPropagation()
                            onOpenChange(false)
                            navigate(`/asset/ledger/${g.table_id}`)
                          }}
                          onKeyDown={(ev) => {
                            if (ev.key === 'Enter') {
                              ev.stopPropagation()
                              onOpenChange(false)
                              navigate(`/asset/ledger/${g.table_id}`)
                            }
                          }}
                        >
                          打开表<ExternalLink className="w-3 h-3" />
                        </span>
                      </button>
                      {isOpen && (
                        <div className="border-t divide-y">
                          {g.records.map((r) => (
                            <div key={r.id} className="p-3">
                              <FieldList data={r.data as Record<string, unknown>} columns={3} emptyText="（空记录）" />
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  )
                })}
              </CardContent>
            </Card>

            {/* ============ 固定资产 / 设备档案 ============ */}
            {search?.fixed_asset && (
              <Card>
                <CardHeader className="py-3"><CardTitle className="text-sm">固定资产</CardTitle></CardHeader>
                <CardContent><FieldList data={search.fixed_asset as Record<string, unknown>} /></CardContent>
              </Card>
            )}
            {search?.archive && (
              <Card>
                <CardHeader className="py-3"><CardTitle className="text-sm">设备档案</CardTitle></CardHeader>
                <CardContent><FieldList data={search.archive as Record<string, unknown>} /></CardContent>
              </Card>
            )}

            {/* ============ BA 问题 ============ */}
            <Card>
              <CardHeader className="py-3">
                <CardTitle className="text-sm flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4 text-amber-500" />BA 问题（{baProblems.length}）
                </CardTitle>
              </CardHeader>
              <CardContent>
                {baProblems.length === 0 ? (
                  <p className="text-sm text-gray-500">无</p>
                ) : (
                  <ul className="space-y-1 text-sm">
                    {baProblems.map((p, i) => (
                      <li key={p.id ?? i} className="border-b border-dashed border-gray-100 py-1 flex flex-wrap gap-2 items-center">
                        <Badge variant={p.status === 'closed' ? 'success' : p.status === 'processing' ? 'warning' : 'destructive'}>
                          {formatValue(p.status ?? '未知')}
                        </Badge>
                        <span className="text-gray-700">{formatValue(p.problem_type ?? '')}</span>
                        <span className="text-gray-400">· {formatValue(p.location ?? p.group_area ?? '')}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </CardContent>
            </Card>

            {/* ============ 配件 ============ */}
            {!!search?.accessories?.length && (
              <Card>
                <CardHeader className="py-3">
                  <CardTitle className="text-sm flex items-center gap-2">
                    <Wrench className="w-4 h-4 text-gray-500" />配件（{search.accessories.length}）
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  {search.accessories.map((a, i) => (
                    <div key={i} className="border-b border-dashed border-gray-100 py-1">
                      <FieldList data={a as Record<string, unknown>} emptyText="—" />
                    </div>
                  ))}
                </CardContent>
              </Card>
            )}
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}

// ==================== 子组件 ====================

function MiniStat({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) {
  return (
    <div className="rounded-lg bg-gray-50 px-3 py-2">
      <div className="text-xs text-gray-500 flex items-center gap-1">{icon}{label}</div>
      <div className="text-lg font-semibold text-gray-900 tabular-nums">{value}</div>
    </div>
  )
}

/** 关联边分组：自动（青）/ 人工（灰），每条带证据与跳转 */
function EdgeGroup({
  title, tone, icon, edges, onNavigate,
}: {
  title: string
  tone: 'cyan' | 'slate'
  icon: React.ReactNode
  edges: DeviceLinkEdge[]
  onNavigate?: (code: string) => void
}) {
  const tones = {
    cyan: { bar: 'border-l-cyan-400', badge: 'bg-cyan-100 text-cyan-800 border-cyan-200', text: 'text-cyan-700' },
    slate: { bar: 'border-l-gray-300', badge: 'bg-gray-100 text-gray-700 border-gray-200', text: 'text-gray-600' },
  } as const
  const t = tones[tone]
  return (
    <div className="space-y-1.5">
      <div className={`text-xs font-medium flex items-center gap-1.5 ${t.text}`}>
        {icon}{title}（{edges.length}）
      </div>
      {edges.map((e) => (
        <div key={e.id} className={`border-l-2 ${t.bar} pl-3 py-1 space-y-0.5`}>
          <div className="flex flex-wrap items-center gap-2 text-sm">
            <Badge variant="outline" className={`text-[10px] ${t.badge}`}>{e.relation_type}</Badge>
            <Badge variant="outline" className="text-[10px]">
              {e.other_kind === 'device' ? '设备' : e.other_kind === 'room' ? '机房' : e.other_kind === 'record' ? '资料编号' : '未知'}
            </Badge>
            <span className="text-gray-500 text-xs">{e.direction === 'out' ? '→' : '←'}</span>
            <button
              type="button"
              className="font-mono text-gray-800 hover:text-blue-600 hover:underline"
              onClick={() => onNavigate?.(e.other_code)}
            >
              {e.other_code}
            </button>
            {e.other_name && <span className="text-gray-500 text-xs">{e.other_name}</span>}
            {e.rule && <span className="text-[10px] text-gray-400">规则 {e.rule}</span>}
          </div>
          {e.evidence && (
            <div className="text-[11px] text-gray-400 leading-relaxed">{e.evidence}</div>
          )}
        </div>
      ))}
    </div>
  )
}
